#############################################################################
# Makefile for building: online_display.app/Contents/MacOS/online_display
# Generated by qmake (2.01a) (Qt 4.8.4) on: Thu Dec 13 15:01:31 2012
# Project:  online_display.pro
# Template: app
# Command: /Users/kntekas/QtCommercialSDK/Desktop/484/cocoa_gcc/bin/qmake -spec ../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/macx-xcode -o online_display.xcodeproj/project.pbxproj online_display.pro
#############################################################################

QMAKE    = /Users/kntekas/QtCommercialSDK/Desktop/484/cocoa_gcc/bin/qmake
online_display.xcodeproj/project.pbxproj: online_display.pro  ../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/macx-xcode/qmake.conf ../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/common/unix.conf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/common/mac.conf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/common/gcc-base.conf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/common/gcc-base-macx.conf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/common/g++-base.conf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/common/g++-macx.conf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/qconfig.pri \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/qt_functions.prf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/qt_config.prf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/exclusive_builds.prf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/default_pre.prf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/mac/default_pre.prf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/mac/dwarf2.prf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/debug.prf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/default_post.prf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/mac/default_post.prf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/mac/objective_c.prf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/unix/thread.prf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/warn_on.prf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/qt.prf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/moc.prf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/mac/rez.prf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/mac/sdk.prf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/resources.prf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/uic.prf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/yacc.prf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/lex.prf \
		../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/include_source_dir.prf \
		/Users/kntekas/QtCommercialSDK/Desktop/484/cocoa_gcc/lib/QtGui.framework/QtGui.prl \
		/Users/kntekas/QtCommercialSDK/Desktop/484/cocoa_gcc/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -spec ../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/macx-xcode -o online_display.xcodeproj/project.pbxproj online_display.pro
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/common/unix.conf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/common/mac.conf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/common/gcc-base.conf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/common/gcc-base-macx.conf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/common/g++-base.conf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/common/g++-macx.conf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/qconfig.pri:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/modules/qt_webkit_version.pri:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/qt_functions.prf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/qt_config.prf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/exclusive_builds.prf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/default_pre.prf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/mac/default_pre.prf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/mac/dwarf2.prf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/debug.prf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/default_post.prf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/mac/default_post.prf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/mac/objective_c.prf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/unix/thread.prf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/warn_on.prf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/qt.prf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/moc.prf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/mac/rez.prf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/mac/sdk.prf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/resources.prf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/uic.prf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/yacc.prf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/lex.prf:
../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/features/include_source_dir.prf:
/Users/kntekas/QtCommercialSDK/Desktop/484/cocoa_gcc/lib/QtGui.framework/QtGui.prl:
/Users/kntekas/QtCommercialSDK/Desktop/484/cocoa_gcc/lib/QtCore.framework/QtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../QtCommercialSDK/Desktop/484/cocoa_gcc/mkspecs/macx-xcode -o online_display.xcodeproj/project.pbxproj online_display.pro

